version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend
    command: yarn dev --host 0.0.0.0
    ports:
      - "5173:5173"                         # Vite default port
    environment:
      VITE_API_BASE_URL: "http://localhost:3000/api/v1"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
