services:
  frontend:
    container_name: earmark_frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev --host 0.0.0.0
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: "http://localhost:3000/api/v1"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
